### ISSUE TITLE
[question] There is any way to perform tests ?

### ISSUE THREAD

**Issue by sen0rxol0** [mailjet/laravel-mailjet#7]
So i'm using laravel for a project and i also would like to use mailjet as our mail service provider.
The only problem was no good support for mailjet api in laravel, i saw this project and i said cool imma try it.
i'm about to push to production and i would like to make some tests before committing.
i've tried but it doesn't seen to be working with laravel.

**Comment by Nightbr** [comment]
If you want to write some tests here is how:

- For unit tests, you can mock Mailjet object/services in order to unit test your code
- For functionnal tests, you can create a new Mailjet free account and use this as your dev/test account to run your testsuite

I think you should be more specific on what you want to achieve exactly with some code example in order to be helped in depth.

**Comment by sen0rxol0** [comment]
i was trying to perform some functional tests, so the issue was on my Mailjet account, as far as it goes this package is working fine. And i agree with you, i was being vague with my question.
